# Generated by Django 5.2.8 on 2025-12-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NucleoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('adiccion', models.CharField(max_length=50)),
            ],
        ),
    ]
