# Generated by Django 5.2.8 on 2025-12-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NucleoModel',
            new_name='Cliente',
        ),
    ]
